Ft sign in to phantom
atlp-rwanda/Dominators-Phantom-BE pull request #11
Opened 2022-04-28 12:04 UTC by tjeaneric

#### What does this PR do?
* Sign in to phantom
* Administrator to use pre-configured login credentials

#### Description of Task to be completed?
* Sign in to phantom where the Administrator will use pre-configured login credentials.
* Have the following endpoint working
`POST /api/v1/user/login`

#### How should this be manually tested?
* `git pull` this branch 
* run `npm install`
* check env.example file and add JWT_SECRET and JWT_EXPIRES_IN to your .env file
* Do migrations with `npm run migrate`
* run `npx sequelize-cli db:seed:all` to create pre-configured credentials for seeders
* run `npm run dev`
* Test the route `POST /api/v1/user/login` in POSTMAN or any other platform for using API

#### Any background context you want to provide?
1. I used the JWT package for hashing the password stored in the Database
2. Documentation can be accessed at `/api-docs`

#### What are the relevant pivotal tracker stories?
*  **The driver, administrator, and operator** should be able to sign in to the app by providing their email & password.
* The API should return a JW token on a successful login.
* The **administrator** should be able to sign in to the app using pre-configured login credentials.
* Appropriate error messages are displayed on unsuccessful attempts

#### Questions:
No.

2022-04-28 12:48 UTC, heiskwizera approved these changes

2022-04-30 16:55 UTC, Angelus123 approved these changes

2022-04-30 16:55 UTC, Angelus123 commented on src/database/seeders/20220418183506-demo-user.js
> +// };
Remove unnecessary!

2022-04-30 16:59 UTC, furebo requested changes
resolve the conflicts

2022-05-01 09:21 UTC, tjeaneric commented on src/database/seeders/20220418183506-demo-user.js
> +// };
Done.

2022-05-02 08:25 UTC, tjeaneric commented
> 

Resolved

2022-05-02 09:48 UTC, gerard1001 approved these changes

2022-05-02 17:31 UTC, Kalimbak approved these changes

2022-05-02 18:08 UTC, furebo approved these changes

2022-05-02 18:08 UTC, furebo approved these changes

2022-05-02 18:08 UTC, merged