Ft crud operation for buses
atlp-rwanda/Dominators-Phantom-BE pull request #13
Opened 2022-05-02 12:31 UTC by Angelus123

2022-05-12 14:10 UTC, kwizeradev reviewed
Squash your commits

2022-05-12 14:10 UTC, kwizeradev commented on src/controllers/busController.js
> +                    message: `Cannot find Bus with id=${id}.`
Translate your responses

2022-05-12 14:12 UTC, tjeaneric commented
Resolve conflicts

2022-05-12 14:29 UTC, tjeaneric requested changes
Resolve conflicts

2022-05-12 14:29 UTC, tjeaneric commented on src/controllers/busController.js
> +        res.status(400).send({
Translate

2022-05-25 06:05 UTC, furebo requested changes
please remove the commented codes and consider squashing the commits

2022-05-25 06:05 UTC, furebo commented on __test__/password.test.js
> +
Please remove these commented code.

2022-05-25 16:02 UTC, closed without merging