Ft profile update
atlp-rwanda/Dominators-Phantom-BE pull request #15
Opened 2022-05-08 17:18 UTC by Kalimbak

What does this PR do?
       Creates or updates the user's profile

Description of Task to be completed?
     As **operator or driver**, I want to be able to update information on my profile, so that others could see updated information about me.
    Appropriate error messages are displayed on unsuccessful attempts

  How should this be manually tested?
        git pull this branch
        run npm install
        check env.example file and add JWT_SECRET and JWT_EXPIRES_IN to your .env file
        Do migrations with npm run migrate
        run npx sequelize-cli db:seed:all to create pre-configured credentials for seeders
        run npm run dev
Test these routes 
        POST /api/v1/profile/update/:id in POSTMAN or any other platform for using API

2022-05-09 07:59 UTC, Angelus123 approved these changes

2022-05-13 12:52 UTC, tjeaneric approved these changes

2022-05-13 12:52 UTC, tjeaneric commented on src/documentation/drivers&operators.js
> +        //   description: 'the Accept-Language',
remove unnecessary

2022-05-13 12:56 UTC, Kalimbak commented on src/documentation/drivers&operators.js
> +        //   description: 'the Accept-Language',
alright

2022-05-13 15:25 UTC, heiskwizera approved these changes

2022-05-19 06:01 UTC, furebo requested changes
Please describe well your PR, squash the commits to one commit and work on requested changes.

2022-05-19 06:01 UTC, furebo commented on Procfile
> +>>>>>>> fixed
Remove unnecessary lines in Procfile

2022-05-19 06:01 UTC, furebo commented on __test__/app.test.js
> +>>>>>>> 3ede931... crud route tests
Please remove these lines

2022-05-19 06:01 UTC, furebo commented on __test__/app.test.js
> +>>>>>>> 3ede931... crud route tests
Remove these lines also

2022-05-19 07:59 UTC, furebo requested changes

2022-05-19 07:59 UTC, furebo commented on Procfile
> +>>>>>>> fixed
Please remove those Unnecessary lines in the file and remember to squash the commits to one commit

2022-05-19 16:15 UTC, furebo approved these changes

2022-05-19 16:15 UTC, merged