Feature assign driver to buses
atlp-rwanda/Dominators-Phantom-BE pull request #22
Opened 2022-06-05 19:44 UTC by fab-ryan

- [x] The operator should be able to assign a driver to a bus.

- [x] The operator should be able to view a paginated list of driver to bus assignments

- [x] The driver should receive a bus assignment and unassignment email & in-app notifications.

- [x] Appropriate error messages are displayed on unsuccessful attempts

2022-06-06 13:12 UTC, aimelive approved these changes
Reviewed!

2022-06-08 09:24 UTC, Anguandia requested changes
Good work, a lot of dedication and a great amount of work done. Apart from the specific in-code comments and change requests, it will be good to consider the following general comments

- Please improve the PR description and harmonize it with team/internal conventions/best practices [here-in](https://github.com/atlp-rwanda/engineering-playbook/tree/master/5.%20Developing/Conventions#branch-naming)
- Test manually locally (with postman) to ensure no feature is broken. Register user is not working
- Tests are not running, please investigate everywhere environment variables are read, in both tests and code. Hint: look into dotenv setup
- You need to clear any junk (data) created by tests after running the tests, else subsequent runs may be greatly impacted by uncleaned residual test data generated by previous runs. Please consider the use of after hooks for this purpose
- Please ensure test quality, it is not sufficient to just test the status code of a response, but also the value of a particular property in the response
- Please do not forget squashing your commits

2022-06-08 09:24 UTC, Anguandia commented on __test__/assign.test.js
> +chai.should();
Test setup could be centralized, instead of repeated per test file

2022-06-08 09:24 UTC, Anguandia commented on __test__/assign.test.js
> +const token = `Bearer ${process.env.admintoken}`;
How are you setting a dynamically generated token in the environment?

2022-06-08 09:24 UTC, Anguandia commented on __test__/assign.test.js
> +        chai.expect(response.body).to.have.property('token');
Please only expect in test cases (it blocks), not in hooks

2022-06-08 09:24 UTC, Anguandia commented on __test__/assign.test.js
> +      .get('/api/v1/assign/a')
Not sure if this simulates an internal error, would be interesting to see that though. At your free time, lookup mocks, spies, etc

2022-06-08 09:24 UTC, Anguandia commented on __test__/auth.test.js
> +        // chai.expect(response.statusCode).to.equal(400);
Why remove this verification, perhaps the code could only be more specific

2022-06-08 09:24 UTC, Anguandia commented on __test__/bus.test.js
>  const token = `Bearer ${process.env.ADMIN_TOKEN}`;
When did you set this token to the environment?

2022-06-08 09:24 UTC, Anguandia commented on src/controllers/authController.js
> +  jwt.sign({ user }, process.env.JWT_SECRET, {
Can't seem to see where dotenv is set up. Please check if environment variables are actually being read, not only here, in tests, and other related files. Consider refactoring .env set up to an application-wide file

2022-06-08 09:24 UTC, Anguandia commented on src/controllers/authController.js
> +};
These are typically middleware functions, authController is a misnomer, this should be a middleware. Please discuss with the team and agree

2022-06-08 09:24 UTC, Anguandia commented on src/database/seeders/20220418183506-demo-user.js
>        ],
Please consider creating an npm script for running seeders

2022-06-08 09:24 UTC, Anguandia commented on src/routes/api/assignDriverRoutes.js
> +import express from 'express';
The file name seems somewhat misleading or confusing, what's your opinion? Drivers are assigned to buses, and buses to routes, not drivers to routes

2022-06-08 09:24 UTC, Anguandia commented on src/routes/index.js
> +routes.use('/unassigned', unassigned);
Good work. Alternatively, assign and un-assign could all be bus routes with an endpoint like this:
`api/v1/buses/:busId/drivers/<:driverId>` where the method is still PATCH and with the driver Id is assign, and without, un-assign. This is just an alternative suggestion, if it interests you, we can discuss, but you may as well continue as is

2022-06-08 09:24 UTC, Anguandia commented on src/utils/paginationHandler.js
> +    const { count: totalItems, rows: result } = data;
Excellent! you added page limit to the pagination, please keep it up

2022-06-08 09:52 UTC, fab-ryan commented on __test__/assign.test.js
> +const token = `Bearer ${process.env.admintoken}`;
I used this for testing incorrect authentication and incorrect role

2022-06-08 10:32 UTC, GilbertUp approved these changes

2022-06-09 07:46 UTC, fab-ryan commented on src/routes/index.js
> +routes.use('/unassigned', unassigned);
Hello What if I make it like this `api/v1/assign/buses/:busid/drivers/:/driverId`

2022-06-09 07:48 UTC, fab-ryan commented on src/utils/paginationHandler.js
> +    const { count: totalItems, rows: result } = data;
The page Limits are getPagination function and after it sort data result those results in getPagingData 
```suggestion
    const getPagination = (page, size) => {
    const limit = size ? + size : 3;
    const offset = page ? page * limit : 0;
    return { limit, offset };
};
```

2022-06-09 07:51 UTC, fab-ryan commented on src/database/seeders/20220418183506-demo-user.js
>        ],
I did that but I have commit it yet

2022-06-09 08:01 UTC, fab-ryan commented on src/routes/index.js
> +routes.use('/unassigned', unassigned);
I have finished this request

2022-06-09 12:36 UTC, fab-ryan commented on __test__/bus.test.js
>  const token = `Bearer ${process.env.ADMIN_TOKEN}`;
I have set them in .env

2022-06-09 12:38 UTC, fab-ryan commented on src/controllers/authController.js
> +  jwt.sign({ user }, process.env.JWT_SECRET, {
I didn't do this task 
about user Login and register

2022-06-09 13:18 UTC, fab-ryan commented on src/routes/api/assignDriverRoutes.js
> +import express from 'express';
No Name it like that because it is router sections

2022-06-10 09:43 UTC, Anguandia commented
Also try to read variables for the better script from the the environment too

2022-06-11 09:15 UTC, Anguandia approved these changes

2022-06-11 09:15 UTC, Anguandia commented on package.json
>          "PORT": 5000
It too, would be good to get these variables (port) from the environment, lest you'll cause conflicts in environments other than your local

2022-06-11 09:19 UTC, furebo approved these changes

2022-06-11 09:20 UTC, merged