Ft set roles permission
atlp-rwanda/Dominators-Phantom-BE pull request #27
Opened 2022-06-16 12:31 UTC by UmuhireJessie

2022-06-16 16:30 UTC, furebo reviewed
Please rebase to resolve the conflicts

2022-06-17 09:11 UTC, furebo reviewed
Create also seeders for roles

2022-06-20 09:36 UTC, fab-ryan approved these changes

2022-06-20 09:37 UTC, Anguandia commented
Good work @UmuhireJessie, please do the following:
- respond to review comments
- give more context in describing how to test this feature
- since we are not using pivotal tracker, you may just include a link to the Trello card for this feature in the section _relevant pivotal tracker stories_
- since you have no screenshots included, you may as well exclude that heading

2022-06-20 09:43 UTC, tjeaneric requested changes
Rebase and Solve Conflicts

2022-06-20 09:43 UTC, tjeaneric commented on src/routes/index.js
> +routes.use('/roles', rolePermissionRoutes)
/roles in two different middlewares

2022-06-20 09:44 UTC, tjeaneric commented
Squash commits

2022-06-20 09:49 UTC, fab-ryan reviewed
Resolve the conflicts

2022-06-20 10:11 UTC, GilbertUp approved these changes

2022-06-21 13:48 UTC, UmuhireJessie commented
> Create also seeders for roles

Done

2022-06-24 19:51 UTC, closed without merging

2022-06-24 19:53 UTC, UmuhireJessie commented
Made a new branch for easing the work of squashing. Its name is `ft-new-set-roles-permission`. Please review it and make a suggestions if any.