Ft profile update
atlp-rwanda/Dominators-Phantom-BE pull request #29
Opened 2022-06-17 12:46 UTC by Kalimbak

What does this PR do?
Creates or updates the user's profile

Description of Task to be completed?
As operator or driver, I want to be able to update information on my profile, so that others could see updated information about me.
Appropriate error messages are displayed on unsuccessful attempts

How should this be manually tested?
git pull this branch
run npm install
check env.example file and add JWT_SECRET and JWT_EXPIRES_IN to your .env file
Do migrations with npm run migrate
run npx sequelize-cli db:seed:all to create pre-configured credentials for seeders
run npm run dev
Test these routes
POST /api/v1/profile/update/:id in POSTMAN or any other platform for using API

2022-06-20 09:28 UTC, Anguandia commented
Good work @Kalimbak, please do the following:
- squash the commits
- try bullet your points if many, in the PR description
- improve the markdown formatting so that the different headings stand out from the rest of the body.
- please use this [markdown](https://www.markdownguide.org/basic-syntax/) guide

2022-06-20 10:12 UTC, GilbertUp approved these changes

2022-06-21 14:48 UTC, aimelive approved these changes

2022-06-22 07:59 UTC, furebo requested changes
Remove the images in uploads folder and put it in .gitignore file . We need to uploads images in the cloud not in the uploads folder .

2022-06-27 07:12 UTC, closed without merging

2022-06-27 07:13 UTC, Anguandia commented
Complete work included in fix PR, already merged