add other fixes on routes endpoint
atlp-rwanda/Dominators-Phantom-BE pull request #38
Opened 2022-07-08 14:24 UTC by UmuhireJessie

### What does this PR do?
- Added how to check permissions if the URL has query parameters
- Changed a `getJourney()` function to have `.findOne()` instead of `.findAll()`
- Changed the `if` statement that checks if one of the `req.body` attributes is empty
- Changed `findAllPermissions()` function to use paginations which are query parameters 
- Added other examples in .env.example
### Description of Task to be completed?

### How should this be manually tested?
- After cloning the repo run `npm i` to install all packages
- For Windows users refer an extra step for installing [`redis`](https://www.youtube.com/watch?v=188Fy-oCw4w&ab_channel=ProgrammingKnowledge2)
- use postman to test different endpoints present in [`index.js`](https://github.com/atlp-rwanda/Dominators-Phantom-BE/blob/develop/src/routes/index.js)
- Run `npm run migrate` to migrate all models in the local database
- Run `npm run seed` to populate the tables with seeders' values
- Run `npm run dev` to start the server manually
- use `http://localhost:3000/api/v1/login` to log in by using admin credentials present in the seeder of the user table. (Change the port **3000** to adhere to your chosen port)
- After login and adding Authorisation in headers, insert the URL with the port and the method you want to use as prescribed in other PRs

### Any background context you want to provide?
The frontend had issues with fetching before which required us to modify the backend for it to work fine.
### What are the relevant pivotal tracker stories?

### Screenshots (if appropriate)

### Questions:

2022-07-08 16:05 UTC, fab-ryan approved these changes

2022-07-09 13:03 UTC, Anguandia requested changes
Good work @UmuhireJessie , please address the few concerns raised herein. Additionally, please replace the property name `Message` in ~/utils/responseHandler.js with `status`, most front-end code checks for the same property by the name of status

2022-07-09 13:03 UTC, Anguandia commented on .env.example
> +USER_HOSTED_PASSWORD=
The existing email-related variables are sufficient. Introducing more variables will only breed confusion. Please remove these variables. Individuals will only give appropriate values in their dev environments while the hosted environments will also be given corresponding appropriate values

2022-07-09 13:03 UTC, Anguandia commented on src/controllers/passwordController.js
> +        ? (resetLink(user_email), msg(res, 200, 'Password reset link was sent'))
Please translate this response too and other succeeding untranslated responses

2022-07-09 13:03 UTC, Anguandia commented on src/controllers/passwordController.js
> +  console.log('REQUEST', req.body);
Remove this, and subsequent console.log statements

2022-07-09 13:03 UTC, Anguandia commented on src/controllers/passwordController.js
> +    return msg(res, 400, 'Bad request, Password Mismatch');
translate

2022-07-09 13:03 UTC, Anguandia commented on src/helpers/sendEmail.js
>  <div>
- This helper file has too much redundancy/repetition. When through with the feedback, consider refactoring this too
- Please revert to the original email credential variable names in the environment, i.e USER_EMAIL, USER_EMAIL_P. these others will cause bugs in existing features `PHANTOM_PASSWORD=
APP_MAIL= 
APP_MAIL_PASSWORD = 
USER_LOCALHOST_PASSWORD= 
USER_HOSTED_PASSWORD= `

2022-07-10 18:55 UTC, GilbertUp approved these changes

2022-07-11 11:47 UTC, UmuhireJessie commented on src/controllers/passwordController.js
> +  console.log('REQUEST', req.body);
Removed

2022-07-11 11:47 UTC, UmuhireJessie commented on src/helpers/sendEmail.js
>  <div>
Done!

2022-07-11 12:24 UTC, fab-ryan approved these changes

2022-07-12 16:11 UTC, Anguandia commented on src/helpers/sendEmail.js
>  <div>
Good!

2022-07-12 16:14 UTC, Anguandia commented on .env.example
> +USER_HOSTED_PASSWORD=
Please act on this one too! We'll merge for now, but please, fix it in the next available PR

2022-07-12 16:15 UTC, Anguandia approved these changes

2022-07-12 16:19 UTC, merged