Bg-fix-update-profile-issues
atlp-rwanda/Dominators-Phantom-BE pull request #39
Opened 2022-07-11 08:36 UTC by aimelive

### What does this PR do?
- Changed PUT method to PATCH method (User might want to update some profile info, not all).
- User profile is created when user account is created/registered by admin. (basics info initially: email, firstName, lastName, and role. Other fields are empty for now).
- User profile is updated, not created when the end point is called.
- Changed Profile.create() method to Profile.update() in updateProfile() function.
- Added `req.file` condition to check if the user added a file so that the profile would be changed by calling `await fileUpload(req)` method.
- Solved an error `req.file.path` path not found.

### Description of Task to be completed?

### How should this be manually tested?
- After pulling this branch `bg-fix-profile-issues` locally and checkout in it. Do `npm i` to get all dependencies.
- Run `npm run migrate` to migrate all models in the local database
- Run `npm run seed` to populate the tables with seeders' values
- Run `npm run dev` to start the server manually
- Use postman to test the endpoints: 
1. First login as an Admin and create new user POST `api/v1/users/login` and  POST `api/v1/users/register` respectively.
2. To check if user account has been created successfully, do GET `api/v1/users/:id` and  to check his profile info do GET `api/v1/users/:id/profile`.
3. To update/change his/her profile info do PATCH `api/v1/v1/users/:id/update`. N.B: In your req.body you will have informations like this or some:  profilePic, lastName, firstName, nationalId, gender, phone, category, bio, province, district, sector, cell or village.
4. Successfully update will show the message: `User Updated Successfully` otherwise will prompt unsuccessfully message.

### Any background context you want to provide?
When we request for the endpoint, the updateProfile function was creating new Profile, instead of updating the existing one. This issue may cause one user to have more than one row in the profile table. 
### What are the relevant pivotal tracker stories?

### Screenshots (if appropriate)

### Questions:

2022-07-11 10:14 UTC, Kalimbak approved these changes

2022-07-11 12:18 UTC, UmuhireJessie requested changes
Great work here @aimelive. I suggest: 
1. when deleting a user a profile can be deleted too unless there is activating or deactivating an account feature in the app. 
2. You may add profile seeders for the admin that we already have, so far they have null profiles

2022-07-11 18:04 UTC, UmuhireJessie approved these changes

2022-07-12 12:43 UTC, UmuhireJessie requested changes
Add seeder for our admins' profiles

2022-07-12 16:29 UTC, Anguandia requested changes
Good work, please do the following respond to pending change requests, then we'll be good to go

2022-07-12 16:29 UTC, Anguandia commented on src/controllers/profilecontroller.js
> +          message: 'No profile match with this id',
Why have you removed the translation?

2022-07-12 16:29 UTC, Anguandia commented on src/controllers/profilecontroller.js
>        Error: error.stack,
do we really need to send the error stack to the user?

2022-07-13 07:42 UTC, Anguandia approved these changes

2022-07-14 08:25 UTC, UmuhireJessie approved these changes

2022-07-14 08:33 UTC, furebo approved these changes

2022-07-14 08:34 UTC, merged