#1102 Ch sequelize cli postgresql 1102
atlp-rwanda/Dominators-Phantom-BE pull request #6
Opened 2022-04-15 11:42 UTC by heiskwizera

### TEST#1 sequelize-cli-postgres-1102 PREQ
1.
i. Make sure that the src/database/models is empty
   ii. Make sure that the src/database/seeders is empty

 ### TEST#2 sequelize-cli-postgres-1102 COMMANDS

- TO CREATE USER MODAL : npm run create-model
- TO MIGRATE : npm run migrate
- TO UNDO ALL MIGRATIONS : npm run undo-migrate
- TO CREATE SEEDER : npm run create-seed
- TO FEED SEEDER use ./data.txt
- TO EXECUTE SEEDER : npm run exec-seed
- TO UNDO CREATED SEED : npm run undo-seed

More information : https://sequelize.org/docs/v6/other-topics/migrations/

2022-04-18 15:20 UTC, tjeaneric approved these changes

2022-04-20 15:17 UTC, Kalimbak approved these changes

2022-04-20 16:02 UTC, Angelus123 approved these changes

2022-04-21 06:33 UTC, furebo requested changes
Rebase the develop and put database credentials in environment variables since now the dotenv is now configured.

2022-04-21 06:33 UTC, furebo commented on data.txt
> +    await queryInterface.bulkDelete('users', null, {});
Please delete this file since you have seeders in seeders folders

2022-04-21 06:33 UTC, furebo commented on package.json
> +    "create-model": "npx sequelize-cli model:generate --name user --attributes name:string,username:string,email:string,password:string",
Remove the create_model command because it will create the user model only once.

2022-04-21 06:33 UTC, furebo commented on data.txt
> +        },
Please remove this file data.txt because you have the seeders.

2022-04-21 06:44 UTC, furebo requested changes
Please also remember to squash the commits

2022-04-23 09:47 UTC, furebo requested changes

2022-04-23 09:47 UTC, furebo commented on .sequelizerc
> +    "config": path.resolve('./src/config', 'config.json'),
Here we need to use config.js because we have it there,instead of json file

2022-04-24 16:32 UTC, furebo approved these changes

2022-04-24 16:32 UTC, merged