Setup Continuous Integration & Quality Assurance pipeline
atlp-rwanda/Dominators-Phantom-BE pull request #8
Opened 2022-04-19 10:27 UTC by Angelus123

**What this PR does** 
This PR is for setting up a testing environment and pipeline.
- [x] Configured Testing environment with Mocha, Chai 
- [ ]Sinon to ensure that all functionalities are tested before deployment.
- [x] GitHub Actions is configured as a continuous integration service used to build and test the app.
- [ ] Configured Heroku Pipeline on Heroku
- [x] GitHub Actions  badge has been added to your repo
- [x] Configure CodeClimate for code analysis and Maintainability checking.

**How could you test?**
git clone
switch to branch ch-setup-ci-and-qa-pipeline
npm install
npm test

2022-04-19 10:35 UTC, Kalimbak approved these changes

2022-04-22 21:07 UTC, heiskwizera approved these changes

2022-04-24 16:48 UTC, furebo requested changes
Hi, Please resolve the conflicts with the develop, and also squash the commits

2022-04-24 16:48 UTC, furebo commented on .github/workflows/phantom.yml
> +>>>>>>> 618b10d7f642f4af3ceaf40d5ba05f61b0db8394
Please resolve the conflicts.

2022-04-25 08:32 UTC, Angelus123 commented on .github/workflows/phantom.yml
> +>>>>>>> 618b10d7f642f4af3ceaf40d5ba05f61b0db8394
The conflict was resolved

2022-04-28 12:11 UTC, Kalimbak approved these changes

2022-04-29 13:20 UTC, tjeaneric approved these changes

2022-04-29 13:20 UTC, tjeaneric commented on src/documentation/index.js
> +import welcome from './welcome.js';
You can remove this .js  if babel is working now.

2022-04-30 14:50 UTC, furebo requested changes

2022-04-30 14:50 UTC, furebo commented on 1
> +#
please remove this file !

2022-04-30 16:31 UTC, Angelus123 commented on src/documentation/index.js
> +import welcome from './welcome.js';
I have already removed it

2022-04-30 16:39 UTC, Angelus123 commented on 1
> +#
I did, Sir

2022-04-30 16:52 UTC, furebo approved these changes

2022-04-30 16:52 UTC, furebo approved these changes

2022-04-30 16:53 UTC, merged