Ch support multiple languages
atlp-rwanda/Dominators-Phantom-BE pull request #9
Opened 2022-04-20 13:49 UTC by Kalimbak

2022-04-20 15:25 UTC, tjeaneric approved these changes

2022-04-20 16:04 UTC, Angelus123 approved these changes

2022-04-21 05:15 UTC, furebo requested changes
Please resolve conflicts in 
- app.js
- config.js
- server.js

2022-04-25 15:46 UTC, heiskwizera approved these changes

2022-04-26 06:03 UTC, furebo requested changes

2022-04-26 06:03 UTC, furebo commented on src/server.js
> +const {port} = config;
Remove line 12 because the port is already declared at line 7 that is causing the error when you start the server. Also remove the commented line 7.

2022-04-26 08:04 UTC, furebo approved these changes

2022-04-26 08:05 UTC, merged